name: Build with Emscripten

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v14
      
      - name: Install Node
        uses: actions/setup-node@v5
          
      - name: Install JDK 24
        run: |
          curl -LO https://download.java.net/java/GA/jdk24.0.2/fdc5d0102fe0414db21410ad5834341f/12/GPL/openjdk-24.0.2_linux-x64_bin.tar.gz
          tar -xzf openjdk-24.0.2_linux-x64_bin.tar.gz

      - name: Dump Minecraft server registries
        run: |
          mkdir notchian
          cd notchian
          curl -Lo server.jar https://piston-data.mojang.com/v1/objects/6bce4ef400e4efaa63a13d5e6f6b500be969ef81/server.jar
          echo "eula=true" > eula.txt
          ../jdk-24.0.2/bin/java -DbundlerMainClass="net.minecraft.data.Main" -jar server.jar --all

      - name: Generate registry headers
        run: |
          node build_registries.js

      - name: Build project
        run: |
          emcc src/*.c -O3 -Iinclude -o bareiron.js
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HLTextureToolsCLI
          path: |
            bareiron.js
  
      - name: Remove previous release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete "continuous" \
                --yes \
                --cleanup-tag \
                --repo "Buggem/bareiron" || true

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: Latest Build (GHA)
          tag: continuous
          allowUpdates: false
          artifacts: bareiron.js
